exports.getConfig = {
  staticResourceLocation: './public/',
};

// 示例数据
exports.getExampleData = {
  pImageU:"这是段落有图片，有文字，有下划线标签<img src='./../public/1.png' width='100' height='100' ><u>这是段落有图片，有文字，有下划线标签</u>",
  pImage:"这是段落有图片，有文字<img src='./public/1.png' width='100' height='100' >这是段落有图片，有文 ",
  ptxt:'只有文字'
};

// 以数学卷子为例子
exports.getSxExampleData = {
  msg: 200,
  data: [
    {
      testnum: '5',
      optionc: 'C、7',
      optiond: 'D、8',
      optiona: 'A、2',
      optionb: 'B、3',
      source: '考金榜',
      templateId: 600047,
      optionnum: 4,
      subjectId: 2,
      createdAt: '2018-02-05 16:44:59',
      optioni: null,
      optionj: null,
      optiong: null,
      solution: '<div class="show-box answer">\n <h2>\n  ［解答］\n </h2>\n <div class="box-bd ue-cnt f-dn">\n  B\n  <hr/>\n  <div>略</div>\n </div>\n</div>',
      collections: null,
      optionh: null,
      optione: null,
      optionf: null,
      ptemplaexer: null,
      id: 199,
      basketid: null,
      collectionnum: 2,
      click: 1000,
      difficulty: '1',
      deletedAt: null,
      fabulousnum: 1,
      coefficient: 0.10000000149011612,
      exercisetypes: null,
      name: '<div class="box-bd ue-cnt f-dn">\n <div>设集合<img src="/sx/source/Upload/2011-03/16/7380ffb6-2157-4868-92dd-db39897aa3d8/paper.files/image023.gif" style="vertical-align:middle;" />，则集合P的非空子集个数是 （）\n</div>',
      orders: '1',
      scorevalue: '2',
      status: true,
      ifinwrong: null,
      exercisetype: '',
      mergetestnum: 0,
      knowledgname: '集合的含义',
      errorrate: '0',
      fromschool: '九江十九中',
      templatename: '单选题',
      tempid: null,
      iscontent: 0,
      questionid: 63161742,
      tempname: null,
      tpapernamem: '2018年10月13日数学考试',
      userId: 1,
      parentId: 0,
      answer: 'B',
      fabulous: null,
      ifbasket: null,
      operatorid: '1' },
    { testnum: '5',
      optionc: 'C、4',
      optiond: 'D、无数个',
      optiona: 'A、2',
      optionb: 'B、3',
      source: '考金榜',
      templateId: 600047,
      optionnum: 4,
      subjectId: 2,
      createdAt: '2018-02-05 16:44:59',
      optioni: null,
      optionj: null,
      optiong: null,
      solution: '<div class="show-box answer">\n <h2>\n  ［解答］\n </h2>\n <div class="box-bd ue-cnt f-dn">\n  C\n  <hr/>\n </div>\n</div>',
      collections: null,
      optionh: null,
      optione: null,
      optionf: null,
      ptemplaexer: null,
      id: 142,
      basketid: null,
      collectionnum: 1,
      click: 1000,
      difficulty: '2',
      deletedAt: null,
      fabulousnum: 0,
      coefficient: 0.3100000023841858,
      exercisetypes: null,
      name: '<div class="box-bd ue-cnt f-dn">\n <span class></span>集合｛x｜x是一条边为2，一个角为30°的等腰三角形｝，其中的元素个数为（　　）\n</div>',
      orders: '2',
      scorevalue: '2',
      status: true,
      ifinwrong: null,
      exercisetype: '',
      mergetestnum: 0,
      knowledgname: '集合的含义',
      errorrate: '0',
      fromschool: '九江十九中',
      templatename: '单选题',
      tempid: null,
      iscontent: 0,
      questionid: 63161995,
      tempname: null,
      tpapernamem: '2018年10月13日数学考试',
      userId: 1,
      parentId: 0,
      answer: 'C',
      fabulous: null,
      ifbasket: null,
      operatorid: '1' },
    { testnum: '5',
      optionc: 'C、3',
      optiond: 'D、4',
      optiona: 'A、1',
      optionb: 'B、2',
      source: '考金榜',
      templateId: 600047,
      optionnum: 4,
      subjectId: 2,
      createdAt: '2018-02-05 16:44:59',
      optioni: null,
      optionj: null,
      optiong: null,
      solution: '解决办法解决办法',
      collections: null,
      optionh: null,
      optione: null,
      optionf: null,
      ptemplaexer: null,
      id: 166,
      basketid: null,
      collectionnum: 0,
      click: 1000,
      difficulty: '1',
      deletedAt: null,
      fabulousnum: 0,
      coefficient: 0.12999999523162842,
      exercisetypes: null,
      name: '<div class="box-bd ue-cnt f-dn">\n <div>设集合<img src="/sx/source/Upload/2014-05/12/c259a537-0617-4189-9394-ec7b07f19c3f/paper.files/image001.png" style="vertical-align:middle;" />，集合<img src="/sx/source/Upload/2014-05/12/c259a537-0617-4189-9394-ec7b07f19c3f/paper.files/image002.png" style="vertical-align:middle;" />，则集合B中元素的个数为(    )\n</div>',
      orders: '3',
      scorevalue: '2',
      status: true,
      ifinwrong: null,
      exercisetype: '',
      mergetestnum: 0,
      knowledgname: '集合的含义',
      errorrate: '0',
      fromschool: '九江十九中',
      templatename: '单选题',
      tempid: null,
      iscontent: 0,
      questionid: 63161959,
      tempname: null,
      tpapernamem: '2018年10月13日数学考试',
      userId: 1,
      parentId: 0,
      answer: 'C',
      fabulous: null,
      ifbasket: null,
      operatorid: '1' },
    { testnum: '5',
      optionc: 'C、6',
      optiond: 'D、7',
      optiona: 'A、4',
      optionb: 'B、5',
      source: '考金榜',
      templateId: 600047,
      optionnum: 4,
      subjectId: 2,
      createdAt: '2018-02-05 16:44:59',
      optioni: null,
      optionj: null,
      optiong: null,
      solution: '<div class="show-box answer">\n <h2>\n  ［解答］\n </h2>\n <div class="box-bd ue-cnt f-dn">\n  C\n  <hr/>\n  <div><br />∵<img src="/sx/source/Upload/2014-05/12/9739450d-67f7-4937-88b3-5b55a963744f/paper.files/image009.png" style="vertical-align:middle;" />，所以<img src="/sx/source/Upload/2014-05/12/9739450d-67f7-4937-88b3-5b55a963744f/paper.files/image010.png" style="vertical-align:middle;" />，∴<img src="/sx/source/Upload/2014-05/12/9739450d-67f7-4937-88b3-5b55a963744f/paper.files/image008.png" style="vertical-align:middle;" />中有6个元素，故选C．<br />考点：集合中元素个数.</div>\n </div>\n</div>',
      collections: null,
      optionh: null,
      optione: null,
      optionf: null,
      ptemplaexer: null,
      id: 163,
      basketid: null,
      collectionnum: 1,
      click: 1000,
      difficulty: '1',
      deletedAt: null,
      fabulousnum: 0,
      coefficient: 0.1599999964237213,
      exercisetypes: null,
      name: '<div class="box-bd ue-cnt f-dn">\n <div>设集合<img src="/sx/source/Upload/2014-05/12/9739450d-67f7-4937-88b3-5b55a963744f/paper.files/image006.png" style="vertical-align:middle;" />,集合<img src="/sx/source/Upload/2014-05/12/9739450d-67f7-4937-88b3-5b55a963744f/paper.files/image007.png" style="vertical-align:middle;" />，则集合<img src="/sx/source/Upload/2014-05/12/9739450d-67f7-4937-88b3-5b55a963744f/paper.files/image008.png" style="vertical-align:middle;" />中有(      )个元素\n</div>',
      orders: '4',
      scorevalue: '2',
      status: true,
      ifinwrong: null,
      exercisetype: '',
      mergetestnum: 0,
      knowledgname: '集合的含义',
      errorrate: '0',
      fromschool: '九江十九中',
      templatename: '单选题',
      tempid: null,
      iscontent: 0,
      questionid: 63161955,
      tempname: null,
      tpapernamem: '2018年10月13日数学考试',
      userId: 1,
      parentId: 0,
      answer: 'C',
      fabulous: null,
      ifbasket: null,
      operatorid: '1' },
    { testnum: '5',
      optionc: 'C、0',
      optiond: 'D、0或4',
      optiona: 'A、4',
      optionb: 'B、2',
      source: '考金榜',
      templateId: 600047,
      optionnum: 4,
      subjectId: 2,
      createdAt: '2018-02-05 16:44:59',
      optioni: null,
      optionj: null,
      optiong: null,
      solution: '<div class="show-box answer">\n <h2>\n  ［解答］\n </h2>\n <div class="box-bd ue-cnt f-dn">\n  A\n  <hr/>\n  <div>当a=0时，方程为1=0不成立，不满足条件<br />当a≠0时，△=a<sup>2</sup>﹣4a=0，解得a=4<br />故选A．</div>\n </div>\n</div>',
      collections: null,
      optionh: null,
      optione: null,
      optionf: null,
      ptemplaexer: null,
      id: 150,
      basketid: null,
      collectionnum: 2,
      click: 1000,
      difficulty: '2',
      deletedAt: null,
      fabulousnum: 1,
      coefficient: 0.25,
      exercisetypes: null,
      name: '<div class="box-bd ue-cnt f-dn">\n <div>若集合A={x∈R|ax<sup>2</sup>+ax+1=0}其中只有一个元素，则a=（　　）\n</div>',
      orders: '5',
      scorevalue: '2',
      status: true,
      ifinwrong: null,
      exercisetype: '',
      mergetestnum: 0,
      knowledgname: '集合的含义',
      errorrate: '0',
      fromschool: '九江十九中',
      templatename: '单选题',
      tempid: null,
      iscontent: 0,
      questionid: 63161929,
      tempname: null,
      tpapernamem: '2018年10月13日数学考试',
      userId: 1,
      parentId: 0,
      answer: 'A',
      fabulous: null,
      ifbasket: null,
      operatorid: '1'
    }
  ]
}
